import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'white',
        
    },
    img:{
        width:'100%',
        height:200,
        objectFit:'contain',
        marginTop:30
    },
    containImg:{
        flexDirection:'row',
        flexWrap:'wrap',
        gap:10,
        paddingTop:20
    },
    subImg:{
        width:80,
        height:60,
        opacity:0.5
    },
    sizeAndNumber:{
        flexDirection:'row',
        paddingTop:10,
        justifyContent: 'space-between',
        paddingBottom:10,
    },
    sizes:{
        width:'48%'
    },
    titleSize:{
        fontSize:20
    },
    textSize:{
        fontSize:18
    },
    size:{
        borderWidth:1,
        borderColor:'#00CCFF',
        padding:5,
        paddingRight:30,
        paddingLeft:30,
    },
    titleNumber:{
        fontSize:20
    },
    textNumber:{
        borderWidth:1,
        borderColor:'#00ccff',
        padding:5,
        paddingRight:10,
        paddingLeft:10,
        fontSize:16
    },
    order:{
        marginTop:30,
    },
    description:{
        paddingTop:20,
    },
    titleDescription:{
        fontSize:24,
        fontWeight:'bold',
    },
    infoDescription:{
        fontSize:18
    },
    feedback:{
        paddingTop:20,
    },
    feedbackTitle:{
        fontSize:24,
        fontWeight:'bold',
    },
    btnStar:{
        position:'relative',
        padding:10,
    },
    star:{
        position:'absolute',
        color:'red',
    },
    perStar:{
        fontSize:18,
    },

    feedbackContent:{
        paddingTop:10,
        paddingBottom:20
    },
    feedbackStar:{
        flexDirection:'row',
        alignItems:'center',
    },
    account:{
        flexDirection:'row',
        alignItems:'center',
        gap:20
    },
    avatar:{
        width:50,
        height:50 ,
        borderRadius:50   
    },
    userName:{
        fontSize:20
    },
    userFeedback:{
        fontSize:18,
        paddingTop:10,
        paddingLeft:20,
    },
    reply:{
        fontSize:16,
        paddingLeft:40
    },
    containWritteFeedback:{
        borderTopWidth:1,
        borderBottomWidth:1,
        marginTop:10,
        marginBottom:10,
        paddingTop:10,
        // paddingBottom:10
    },
    titleWrite:{
        fontSize:18,
        paddingBottom:10
    },
    ipWrite:{
        borderBottomWidth:1,
        height:50,
        marginBottom:20,
        fontSize:18
    },
    containMessageFeedback:{
        marginTop:5,
        marginBottom:5,
        padding:7,
        backgroundColor:'#e8e8e8'
    },
    textPrice:{
        fontSize:20,
        paddingBottom:10
    },

    // active
    starAcitve:{
        display:"flex"
    },
    starNoAction:{
        display:"none"
    }   
})